apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer # Use NodePort if LoadBalancer is not available
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 8090       # External port
      targetPort: 8090 # Container port
